server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/assignment
    username: root
    password: 1234

  jpa:
    show-sql: true

  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 3000
          community-client:
            url: ""
            dismiss404: true

springdoc:
  swagger-ui:
    path: /api-docs
    url: /docs/swagger.yaml
